=== 1-Byte/mobility-database-catalogs/schemas/gtfs_schedules_source_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "The Mobility Catalogs static source schema.",
  "type": "object",
  "properties": {
    "mdb_source_id": {
      "type": "string",
      "description": "The Mobility Database ID of the source."
    },
    "name": {
      "type": "string",
      "description": "The name of the source."
    },
    "location": {
      "type": "string",
      "description": "The location name of the source."
    },
    "country_code": {
      "type": "string",
      "description": "The country code of the source."
    },
    "bounding_box": {
      "type": "object",
      "description": "The bounding box of the source.",
      "oneOf": [
        {
          "properties": {
            "minimum_latitude": {
              "type": "number",
              "minimum": -90,
              "maximum": 90
            },
            "maximum_latitude": {
              "type": "number",
              "minimum": -90,
              "maximum": 90
            },
            "minimum_longitude": {
              "type": "number",
              "minimum": -180,
              "maximum": 180
            },
            "maximum_longitude": {
              "type": "number",
              "minimum": -180,
              "maximum": 180
            },
            "extracted_on": {
              "type": "string",
              "format": "date-time"
            }
          }
        },
        {
          "properties": {
            "minimum_latitude": {
              "type": "null"
            },
            "maximum_latitude": {
              "type": "null"
            },
            "minimum_longitude": {
              "type": "null"
            },
            "maximum_longitude": {
              "type": "null"
            },
            "extracted_on": {
              "type": "string",
              "format": "date-time"
            }
          }
        }
      ],
      "required": ["minimum_latitude", "maximum_latitude", "minimum_longitude", "maximum_longitude", "extracted_on"]
    },
    "data_type": {
      "type": "string",
      "description": "The data type of the source.",
      "enum": ["gtfs"]
    },
    "urls": {
      "type": "object",
      "properties": {
        "auto_discovery": {
          "type": "string",
          "description": "The stable auto-discovery url of the source as given by the provider.",
          "pattern": "^(http|https|ftp):\/\/[a-zA-Z0-9.,~#{}():&/%='?_/-]+$"
        },
        "license": {
          "type": "string",
          "description": "The url to the license of the source as given by the provider.",
          "pattern": "^(http|https|ftp):\/\/[a-zA-Z0-9.,~#{}():&/%='?_/-]+$"
        },
        "latest": {
          "type": "string",
          "description": "The Mobility Archives stable url for the latest dataset version of the source.",
          "pattern": "^(http|https|ftp):\/\/[a-zA-Z0-9.,~#{}():&/%='?_/-]+$"
        }
      },
      "required": ["auto_discovery", "license", "latest"]
    }
  },
  "required": ["mdb_source_id", "name", "location", "country_code", "bounding_box", "data_type", "urls"]
}

=== 1-Byte/mobility-database-catalogs/catalogs/gtfs/schedules/mdb-src-gtfs-london-transit-commission-ca.json
{
    "mdb_source_id": "mdb-src-gtfs-london-transit-commission-ca",
    "name": "London Transit Commission",
    "location": "London, Ontario",
    "country_code": "CA",
    "bounding_box": {
        "minimum_latitude": 42.905244,
        "maximum_latitude": 43.051188,
        "minimum_longitude": -81.36311,
        "maximum_longitude": -81.137591,
        "extracted_on": "2022-02-01T17:20:21+00:00"
    },
    "data_type": "gtfs",
    "urls": {
        "auto_discovery": "http://www.londontransit.ca/gtfsfeed/google_transit.zip",
        "license": "https://www.londontransit.ca/open-data/ltcs-open-data-terms-of-use/",
        "latest": "https://storage.googleapis.com/storage/v1/b/archives_latest/o/mdb-src-gtfs-london-transit-commission-ca.zip?alt=media"
    }
}
